name: Validate PR

on:
  pull_request:
    branches: [ main ]

jobs:

  vcpkg-win:
    name: vcpkg-win
    runs-on: windows-2022
    steps:
    - name: Installing vcpkg (windows)
      run: |
        cd ..
        git clone https://github.com/Microsoft/vcpkg.git
        cd vcpkg
        git checkout --force 5962cf5a3bfc2124e8de991a4e45a8edcb3b4c69
        .\bootstrap-vcpkg.bat
        echo VCPKG_ROOT: $VCPKG_ROOT

  vcpkg-linux:
    name: vcpkg-lunux
    runs-on: ubuntu-20.04
    steps:
    - name: Installing vcpkg (windows)
      run: |
        cd ..
        git clone https://github.com/Microsoft/vcpkg.git
        cd vcpkg
        git checkout --force 5962cf5a3bfc2124e8de991a4e45a8edcb3b4c69
        .\bootstrap-vcpkg.sh
        echo VCPKG_ROOT: $VCPKG_ROOT

  vcpkg-macos:
    name: vcpkg-macos
    runs-on: macos-11
    steps:
    - name: Installing vcpkg (windows)
      run: |
        cd ..
        git clone https://github.com/Microsoft/vcpkg.git
        cd vcpkg
        git checkout --force 5962cf5a3bfc2124e8de991a4e45a8edcb3b4c69
        .\bootstrap-vcpkg.sh
        echo VCPKG_ROOT: $VCPKG_ROOT
