name: Validate PR

on:
  pull_request:
    branches: [ main ]

jobs:

  vcpkg-win:
    name: vcpkg-win
    runs-on: windows-2022
    steps:
    - name: Installing vcpkg (windows)
      run: |
        cd ..
        git clone https://github.com/Microsoft/vcpkg.git
        cd vcpkg
        git checkout --force 2022.03.10
        .\bootstrap-vcpkg.bat
        ls ..\vcpkg

  vcpkg-linux:
    name: vcpkg-linux
#    runs-on: ubuntu-20.04
    runs-on: self-hosted
    steps:
    - name: Installing vcpkg (windows)
      shell: bash
      run: |
        cd ..
        git clone https://github.com/Microsoft/vcpkg.git
        cd vcpkg
        git checkout --force 2022.03.10
        ./bootstrap-vcpkg.sh
        ls ../vcpkg

  vcpkg-macos:
    name: vcpkg-macos
    runs-on: macos-11
    steps:
    - name: Installing vcpkg (windows)
      run: |
        cd ..
        git clone https://github.com/Microsoft/vcpkg.git
        cd vcpkg
        git checkout --force 2022.03.10
        ./bootstrap-vcpkg.sh
        echo VCPKG_ROOT: $VCPKG_ROOT
        ls ../vcpkg
