name: Validate PR

on:
  pull_request:
    branches: [ main ]

jobs:

  clang-format:
    name: Formatting Check
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: clang-format
      uses: jidicula/clang-format-action@v4.6.2
      with:
        clang-format-version: '12'
        check-path: "src**/*"
