name: Validate PR

on:
  pull_request:
    branches: [ main ]

jobs:

  clang-format:
    name: Formatting Check
    runs-on: ubuntu-latest
    strategy:
          matrix:
            path:
              - 'src_one'
              - 'src_two'

    steps:
    - uses: actions/checkout@v2
    - name: clang-format ${{ matrix.path }}
      uses: jidicula/clang-format-action@v4.6.2
      with:
        clang-format-version: '12'
        check-path: ${{ matrix.path }}

  checkout-and-check-formatting:
      runs-on: ubuntu-latest
      strategy:
            matrix:
              path:
                - 'src_one'
                - 'src_two'

      steps:
      - uses: actions/checkout@v2
      - name: Run clang-tidy
        uses: HorstBaerbel/action-clang-tidy@1.2
        with:
          scandir: ${{ matrix.path }}
          builddir: 'build'
          extensions: 'h,cpp'
