name: Create Release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  get-tag:
    runs-on: ubuntu-latest
    outputs:
      tag-name: ${{steps.get-tag.outputs.tag}}
    steps:
      - name: Set RELEASE_VERSION env
        id: get-tag
        run: |
          echo "${GITHUB_REF#refs/*/}"
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
          echo "::set-output name=tag::${GITHUB_REF#refs/*/}"
#
#    steps:
#      - name: compute tag
#        id: compute-tag
#        run: |
#          $GITHUB_FULLREF="${{ github.ref }}"
#          $RELEASE_VERSION=$GITHUB_FULLREF -replace 'refs/.*/', ''
#          echo Version $RELEASE_VERSION
#          echo "::set-output name=tag::$RELEASE_VERSION"

  use-tag:
    strategy:
      matrix:
#        platform: [ubuntu-latest, windows-latest, macos-latest]
        platform: [ubuntu-latest]

    runs-on: ${{matrix.platform}}
    needs: get-tag
    steps:
    - name: Show tag
      run: |
        echo ${{needs.get-tag.outputs.tag-name}}
#         echo ${{env.RELEASE_VERSION}}
