name: Create Release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
#  get-version-tag:
#    runs-on: ubuntu-latest
#    outputs:
#      version: ${{steps.get-tag.outputs.tag}}
#      prerelease: ${{steps.get-prerelease.outputs.value}}
#    steps:
#      - name: Set version output
#        id: get-tag
#        run: |
#          echo "GITHUB_REF: ${GITHUB_REF}"
#          echo "GITHUB_REF_NAME: ${GITHUB_REF_NAME}"
#          echo "${GITHUB_REF#refs/*/}"
#          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
#          echo "::set-output name=tag::${GITHUB_REF#refs/*/}"

#      - name: Set prerelease output
#        id: get-prerelease
#        uses: haya14busa/action-cond@v1
#        with:
#          cond: ${{contains(github.ref, '-pre')}}
#          if_true: "true"
#          if_false: "false"

  use-tag:
    strategy:
      matrix:
#        platform: [ubuntu-latest, windows-latest, macos-latest]
        platform: [ubuntu-latest]

    runs-on: ${{matrix.platform}}
#    needs: get-version-tag
    steps:
    - name: Check prerelease
      id: get-prerelease
      uses: haya14busa/action-cond@v1
      with:
        cond: ${{contains(github.ref, '-pre')}}
        if_true: "true"
        if_false: "false"
    - name: Show tag
      run: |
        echo "version: ${GITHUB_REF_NAME}"
        echo "prerelease: ${{steps.get-prerelease.outputs.value}}"
#         echo ${{env.RELEASE_VERSION}}
